### ISSUE TITLE
kogu-server params

### ISSUE THREAD

**Issue by budmitr** [kogu-io/kogu#4]
Hey there,

Do you have any parameters for kogu-server?
I can't find anything in documentation neither can I use help of kogu-server command.

Would be also cool to have `kogu-server help` to check available commands, and have some of them like `kogu-server --version` so I can check and ensure latest version installation or `kogu-server --port 2345` so I can use non-default port and so on

Cheers

**Comment by rababarber** [comment]
Hi.
Thanks for feedback. Kogu server port is actually configurable. However you are correct about that information not being (until now intentionally) documented. I decided to write short topic about that to the docs. It's here: https://docs.kogu.io/server.html

**Comment by budmitr** [comment]
Thanks! This was really helpful -- I run kogu within a docker container and it became a bit easier to expose the port rather than creating a nginx proxy :)
